version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ./backend/.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  backend:
    container_name: backend
    # network_mode: bridge
    command: ./start.sh postgres:5432
    networks:
      - default
    stdin_open: true
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules/
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    # network_mode: bridge
    networks:
      - default
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  postgresDB:
  redisDB:
  pgadmin-data:

networks:
  default: